### ISSUE TITLE
Compilation error on rust 1.80

### ISSUE THREAD

**Issue by St333p** [rust-amplify/amplify-derive#44]
I get the following compilation error on master after updating rust to 1.80:

```
error: associated constant `DERIVE` is never used
   --> amplify-derive/src/wrapper.rs:116:11
    |
114 | pub trait FromPath: Sized + Copy + Ord {
    |           -------- associated constant in this trait
115 |     const IDENT: &'static str;
116 |     const DERIVE: &'static str;
    |           ^^^^^^
    |
note: the lint level is defined here
   --> amplify-derive/src/lib.rs:28:5
    |
28  |     dead_code
    |     ^^^^^^^^^
```

**Comment by dr-orlovsky** [comment]
rustc 1.80 bug is fixed in `amplify-derive` v4.0.1 just published to crates.io. Use `cargo update` to get it into your `Cargo.lock`
